#Pretty much all the strings that the bot sends. This is in a list so adding languages is easy
loadingSong = ["Loading Song....", "You don't tell me what to do. I'll take my sweet ass time finding that", "تحميل الاغنية .... الرجاء الانتظار"]
nowPlaying = ["Now playing: ", "Your ears have the misfortune of hearing: ", "الاغنية الحالية: "]
noVC = ["Sorry, it appears you're not in a VC", "Where are you? Oh that's right! You're not in a VC. Get your keister in a VC and try again", "عذرا ، أنت لست في قناة"]
cantFindSong = ["Sorry, I couldn't find that song", "Really? That's the best you could come up with? Try again, next time pick a song that actually exists, dofus", "آسف ، لم أجد تلك الأغنية"]
leaveVC = ["Bye!", "Never liked you anyway", "الى اللقا!ء"]
notInVC = ["I'm not in a VC 😀", "Okay, seeing as your brain is non-existant, I'm gonna explain this to you. ***In order for me to do stuff, i kinda have to already be in a vc...*** Try again, imbecile", "أنا لست في قناة 😀"]
fOff = ["Was it something I said 😢", "You realize I have admin perms right? You don't wanna start beef. Say that again and you're getting kicked", "وداعا 😢"]
skipTrack = ["Skipped!", "OH MY GOD FINALLY ME EARS WERE BLEEDING", "تم تخطي الأغنية"]

youreNotInVC = ["Sorry, you have to be in a VC to use this command", "How are you going to listen to music when you're not even in a VC you nimrod", "عذرًا ، يجب أن تكون في قناة لاستخدام هذه الميزة"]
nothingsPlaying = ["Nothing's playing 😀", "How do I pause something that isn't playing? That's right, I don't. Imbecile", "لا يوجد تشغيل للموسيقى 😀"]
nothingsPaused = ["Nothing's paused 😀", "How do I play something that isn't paused? That's right, I don't. Imbecile", "لا يوجد شيء متوقف"]
addedToQueue = ["Added to the Queue!", "You don't tell me what to do, i'll play that song when I feel like it", "تمت إضافة تلك الأغنية إلى قائمة الانتظار"]
wrongVC = ["You need to be in the same voice channel as me to use this command", "Nice try loser. You need to be in my VC to use this command", "يجب أن تكون في قناتي لاستخدام هذه الميزة"]
resume = ["Resumed!", "Why are we going back to this? I feel like my AUX cable is coming out of a trash can", "تم استئناف الأغنية"]
songPaused = ["Paused!", "OH MY GOD FINALLY ME EARS WERE BLEEDING", "تم توقيف الأغنية"]
currentQueue = ["The queue is: ", "The queue is (unfortunately): "]
emptyQueue = ["The queue is empty", "The queue is (fortunately) empty", "قائمة الانتظار فارغة"]
noSong = ["There's no song playing", "There's no song playing (Thank god)", "لا توجد أغنية تلعب"]
looping = ["Loop toggled to: ", "You are an idiot: ", "تم تشغيل تكرار الأغنية: "]
automatedMessage = ["This is an automated message", "I'm just a bot.... or am i... 🔪", "هذه رسالة آلية"]
notification = [":bell: tMusic Notification", ":bell: tMusic Notification", ":bell: إشعار tMusic"]
error = [":x: tMusic error", ":x: tMusic error", ":x: خطأ tMusic"]
languageSet = ["Language set!", "Language set!", "تم تحديد اللغة!"]